# example netlify.toml
[build]
  command = "npm build"
  functions = "netlify/functions"
  publish = "build"

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
